### PR TITLE
Update SqlAlchemy setup and move to Chromedriver

### PR DESCRIPTION
**Pull request by jonjrodriguez**
This PR makes our codebase more closely structured to the professor's example project. There were still issues running all the behave tests however.

In addition, it adds Chrome and chromedriver to the vagrant box so it can use headless chrome to run our selenium tests. This change makes all the tests work correctly and continue to pass after multiple runs. I suspect there was an issue with the version of `PhantomJS` we were using.

All unit tests and scenarios pass!

### CODE REVIEW

**Comment by carpetri** [comment]
Nosetests are not passing for me.
I did vagrant provision. Still not sure what's happening. But it seems to be a connection error to the db.

**Comment by radhikamattoo** [comment]
@carpetri destroying & re-provisioning worked for me

**Comment by carpetri** [comment]
I'm getting the next error when I vagrant up.

 The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!


          rm -f /var/lib/vagrant/cids/378e3bcac6c74262787a896950a32586db5edb9f
          docker run --cidfile=/var/lib/vagrant/cids/378e3bcac6c74262787a896950a32586db5edb9f -d --name mariadb --restart=always --restart=always -d --name mariadb -p 3306:3306 -v /var/lib/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root mariadb
        

Stdout from the command:

282b6bcaa58160dac4ce853d6efa3844ce1f2db7b2b3bdce5b875376dbabeb9c


Stderr from the command:

docker: Error response from daemon: driver failed programming external connectivity on endpoint mariadb (dc40c8cd2f72b932070a27d42bbbf5755585c8a0f9398fa7fac1407c5783a209): Bind for 0.0.0.0:3306 failed: port is already allocated.

**Comment by jonjrodriguez** [comment]
Try vagrant down > vagrant up.

**Pull request merged**
