### PR TITLE
Flask Skeleton with requirements.txt

### PR DESCRIPTION
**Pull request by radhikamattoo**
Running: 

`pip install -r requirements.txt`
then 
`python server.py` 
will give you a server running at localhost:5000

### CODE REVIEW

**Comment by carpetri** [comment]
It actually should be  in an __init__.py file such as the one in the lab from class:

https://github.com/nyu-devops/lab-flask-bdd/blob/master/app/__init__.py

**Comment by thoughts1053** [comment]
@carpetri I think that example is more robust than what we're trying to do. I think a simple `server.py` like @radhikamattoo currently has will be fine for now.

**Comment by radhikamattoo** [comment]
@thoughts1053 my bad, just another commit for it

**Comment by carpetri** [comment]
Flask skeleton ready

**Pull request merged**
