### PR TITLE
Scenario to list shopcarts

### PR DESCRIPTION
**Pull request by carpetri**
To run:
```
cd /vagrant
python3 run.py &
behave
```

All test should pass.

### CODE REVIEW

**Comment by radhikamattoo** [comment]
I believe we're supposed to mimic the professor's code, where we interact with the UI like he does [here](https://github.com/nyu-devops/lab-flask-bdd/blob/43d4d82d015ede6f566e7ef5785deb34758bf36b/features/pets.feature#L27). @thoughts1053 is workin on that now, so we can wait for his PR before working on other scenarios

**Comment by carpetri** [comment]
Oh i see. I'll wait. Thanks @radhikamattoo

**Comment by thoughts1053** [comment]
@carpetri I think master needs to be merged into this and then the test redone for the new UI.

**Comment by radhikamattoo** [comment]
Just to be consistent, I changed `in the shopcarts table` to `in the results`. 

I also changed the given ids to `2`, `3`, and `4`, because the following create shopcart test tries to create a shopcart with id `1` and technically doesn't go through because it already exists, but the test still passes. I added an extra assertion there to make sure the `form-error` id has no text when you create a shopcart.

**Pull request merged**
