### PR TITLE
Prune empty shopcarts

### PR DESCRIPTION
**Pull request by thoughts1053**
This will delete all empty shopcarts (no products) via a `PUT` request to `shopcarts/prune`. All tests passing for model and server and kept code coverage the same.

I returned the same type of response as a delete `HTTP_204_NO_CONTENT` as this is just deleting multiple items at a time.

### CODE REVIEW

**Comment by radhikamattoo** [comment]
Should this maybe be a `DELETE` request on `shopcarts/prune`? A `PUT` request that's deleting entire objects doesn't seem right @carpetri

**Comment by thoughts1053** [comment]
@radhikamattoo I went along with the issue, which I think went along with the notes. It's updating the shopcart store as a whole so I can see `PUT`, but it's also only deleting carts so I understand `DELETE`. I can go either way.

**Comment by carpetri** [comment]
It's an action so I think it can go both ways as @thoughts1053 says . We should leave it as PUT to be consistent with the issue rigth?

**Comment by radhikamattoo** [comment]
We could always modify the issue to say it's a `DELETE` request. I think it makes sense to change it to reflect the nature of the action, which is deleting empty shopcarts. @thoughts1053 @carpetri

**Comment by carpetri** [comment]
It might seem more natural to have it as DELETE. I'm ok with both.

**Comment by thoughts1053** [comment]
So actions are more like RPC than REST, so we don't have to be as strict. Really we could also normalize it to be a `POST` to the action so the action name is the description more so than the http verb.

**Comment by thoughts1053** [comment]
So now I'm actually between `POST` and `DELETE`. Whichever you prefer @radhikamattoo

**Comment by thoughts1053** [comment]
👍

**Pull request merged**
