### PR TITLE
Setup the pipeline in bluemix

### PR DESCRIPTION
**Pull request by carpetri**

### CODE REVIEW

**Comment by jonjrodriguez** [comment]
Do none of the VCAP services test work? What's the errors you're getting on Bluemux?

**Comment by carpetri** [comment]
Tests don not pass, but more importantly, they I think they do not make a lot of sense they are not actually testing anything. But feel free to fix them @jonjrodriguez  

I sent you the log in slack: https://slack-files.com/T6XHHFGN7-F8B3CRZ2R-50702b6db1

**Comment by jonjrodriguez** [comment]
Let's really make sure to squash this when merging. :)

**Comment by jonjrodriguez** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/31db54b9-a293-4c16-8c10-53e94ed2b1e3 "toolchain-nyu-shopcart-service-f17"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/f9530127-4ee8-45d4-8ffe-8ff7aa73f06d "pipeline-nyu-shopcart-service-f17") deployed [shopcarts](https://github.com/nyu-devops-echo/shopcarts/releases/tag/deploy-ibm-yp-us-south-nyu-echo-team-f17-dev-20171210-200852 "deploy-ibm-yp-us-south-nyu-echo-team-f17-dev-20171210-200852") to [dev](https://console.bluemix.net/apps/88786953-cff5-46cb-a093-bee73a357474?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-echo-team-f17:dev"), including commit 76332af923957329ea6ab4d736d73dcbaea9865c

**Comment by jonjrodriguez** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/31db54b9-a293-4c16-8c10-53e94ed2b1e3 "toolchain-nyu-shopcart-service-f17"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/f9530127-4ee8-45d4-8ffe-8ff7aa73f06d "pipeline-nyu-shopcart-service-f17") deployed [shopcarts](https://github.com/nyu-devops-echo/shopcarts/releases/tag/deploy-ibm-yp-us-south-nyu-echo-team-f17-prod-20171210-201409 "deploy-ibm-yp-us-south-nyu-echo-team-f17-prod-20171210-201409") to [prod](https://console.bluemix.net/apps/b7e22d67-ab14-4044-b01c-0ca9f7a40673?env_id=ibm:yp:us-south "ibm:yp:us-south:nyu-echo-team-f17:prod"), including commit 76332af923957329ea6ab4d736d73dcbaea9865c

**Pull request merged**
