### PR TITLE
Adding basic description to the root

### PR DESCRIPTION
**Pull request by carpetri**
Adding a basic description to the root.
Modified the test_index accordingly.

### CODE REVIEW

**Comment by carpetri** [comment]
We still don't have links so I decided to leave that out for now... 
We can add them later since we will probably have a full html file describing the API and we are doing MVP.

**Comment by thoughts1053** [comment]
@carpetri please don't merge your own branch.

**Comment by carpetri** [comment]
Should we restore this? @thoughts1053 @radhikamattoo

**Comment by thoughts1053** [comment]
Eh. We're going to be adding swagger soon which will make this moot I think.

**Pull request merged**
